

production:
  adapter: mysql2
  database: nanba_stage
  server: 192.168.0.179
  host: 192.168.0.179
  port: 3306
  username: root
  password: root
  encoding: utf8
  reconnect: true
development:
  adapter: mysql2
  database: nanba_stage
  server: 192.168.0.179
  host: 192.168.0.179
  port: 3306
  username: root
  password: root
  encoding: utf8
  reconnect: true


test:
  adapter: mysql2
  database: redmine_test
  host: localhost
  username: root
  password: root
  encoding: utf8

